module.exports.majors = {
  majors: [
      "Accounting",
      "Applied Language",
      "Art",
      "Art History",
      "Art Therapy",
          "Graphic Design",
          "Studio Art",
      "Biology",
      "Business",
      "Business Administration",
          "Business Administration" ,
          "Global Business",
          "Human Resource Management",
        "  Small Business and Entrepreneurship",
      "Chemistry",
        "Communication and Media Studies",
          "Broadcast Journalism",
          "Filmmaking",
          "Radio/TV Performance",
      "Computer Information Systems (CIS)",
        "  Business Systems",
          "Information Technology",
      "Criminal Justice",
    "  Education",
          "Early Childhood",
        "  Elementary",
          "Secondary",
          "Special Education",
      "English",
    "Financial Economics",
    "Healthcare Administration",
    "Health Science",
      "History",
      "Individualized Majors",
      "Marketing",
      "Mathematics",
      "Medical Technology",
      "Music",
      "Natural and Physical Science",
      "Nursing",
      "Philosophy",
      "Political Science",
      "Psychology",
      "Public Health Education",
      "Social Studies",
      "Sociology",
      "Spanish",
      "Sport Management",
      "Theology",
]
}
